### ISSUE TITLE
Undefined name 'layerRelation'

### ISSUE THREAD

**Issue by cclauss** [huggingface/hmtl#1]
[flake8](http://flake8.pycqa.org) testing of https://github.com/huggingface/hmtl on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./hmtl/models/layerRelation.py:96:60: F821 undefined name 'layerRelation'
                    regularizer: RegularizerApplicator) -> "layerRelation":
                                                           ^
1     F821 undefined name 'layerRelation'
1
```

**Comment by VictorSanh** [comment]
That's right, thanks for pointing that out.
