### ISSUE TITLE
How to finetune on customized dataset?

### ISSUE THREAD

**Issue by tingkai-zhang** [huggingface/hmtl#10]
Hi, thanks for this beautiful work!

I have a coreference dataset that has format 
`Text,	Pronoun,	Pronoun-offset,	A,	A-offset,	A-coref,	B,	B-offset,	B-coref`

Example:

> Tom  went out and bought a book. He found it very interesting. 

Then, 'Tom' is the Pronoun, A is 'He', A-coref is True, B is 'it', B-coref is False, off-sets indicates each token's position.

Can I use HMTL to finetune on such dataset?
If so, how should I modify the json file, dataset reader?
If not, how can I use HMTL to predict the conference pair of the `Pronoun` in each text? Like predict which word in the text corefers the `Pronoun`?

I appreciate your help!

**Comment by VictorSanh** [comment]
Hey!

Thanks for your interest!

I've experimenting using transfer learning to fine tune on another coreference dataset, so yes, it should be possible.
I think you have two choices here:
1/ You convert your dataset format to a CoNLL20120-coreference format. It should be feasible if I understand correctly that the offsets are the token positions. Then it is pretty much just replacing the dataset paths in the config files and call `fine_tune.py` (and probably some minor parameters to add such as the pre-trained weights to fine-tune).
2/ You implement a `DatasetReader` (see `hmtl/dataset_readers`) that support your dataset format and modify the config file to call this specific dataset reader type (and then call `fine_tune.py`, it should be seamless once you add another dataset reader).

Victor

**Comment by VictorSanh** [comment]
Something to keep in mind is that the final return of the coreference module is the coreference clusters: in your example, there is one cluster {`Tom`, `He`}, but there could be more mentions in this cluster. From the cluster, it is trivial to get the coreferent pairs.

**Comment by tingkai-zhang** [comment]
Thank you!

**Comment by tingkai-zhang** [comment]
Hi, I encountered another question...

There is no coreference pair in my dataset.
What happens when the gold cluster is empty?

I tried assigned the gold cluster as `[]` but it will be an error when `scorer` calculates the score. 

What is a appropriate way to deal with empty golder cluster?(Both `A-coref` and `` B-coref` are false)

**Comment by VictorSanh** [comment]
I am not sure to fully understand what you dataset format is and more specifically what does `A-coref=False` and `B-coref=False` mean...
From what I see, when there are no coreference links, there should not be any cluster id in a conll formatted file, and thus `canonical_clusters` in the `dataset reader` should be an empty list, and then `gold_clusters` should also be an empty list.
But naturally, you want to train your model on these "negative" examples so it is able to detect when there are no coreference links.
