### ISSUE TITLE
What columns of the *._conll are used for NER training? 

### ISSUE THREAD

**Issue by poojanarayanc** [huggingface/hmtl#11]
Not an issue, but a query really. Have been looking at training my own models, just wondered if all columns of the *._conll files are used for NER training or is it just the NER tags?

**Comment by VictorSanh** [comment]
Hello, thanks for your interest.
For training NER, only the column with the NER tags are actually retained when loading the training set (and obviously the column with the text too).
Victor

**Comment by poojanarayanc** [comment]
Thanks, that's very helpful to know!
