### ISSUE TITLE
A-RS-GM model

### ISSUE THREAD

**Issue by pvcastro** [huggingface/hmtl#4]
Regarding your paper, specifically tables 4 and 5, and is the meaning of the "RS" in **A-RS-GM**? This has no reference in any other part of the paper.

Thanks, and congrats for the paper!

**Comment by VictorSanh** [comment]
Thanks!

"RS" refers to "Rahman splits" i.e. the splits introduced by Rahman and Ng 2009.
So A-RS-GM is basically the same thing as A-GM.
