### ISSUE TITLE
Chinese is not supported？

### ISSUE THREAD

**Issue by MrRace** [huggingface/hmtl#5]
I try Chinese sentense,but it seems have not support Chinese yet？
My test sentence:“中国的首都是北京”

**Comment by VictorSanh** [comment]
Hello,

Thanks for your interest!

Yes, the demo (along with the released weights) are for English. So Chinese is not supported right now.
There is no plan in the short term to release a Chinese version but I would be glad to feature a chinese version if you are willing to train it.

Also, I realize that the README might not be clear enough on this, so I just added some clarification.

Victor

**Comment by MrRace** [comment]
Yeah,I would like to train a Chinese version.If you have some additional advice on the details, you can tell me in advance.

**Comment by VictorSanh** [comment]
You should replace the dataset in the `data` folder for all the tasks you want to train. The default config file consider 4 tasks (NER, EMD, Coreference and Relation Extraction). For more details on how to setup the data, I invite you to read this thread: https://github.com/huggingface/hmtl/issues/2

Make sure that you change the paths in the configuration file too.

Last, make sure that you modify the pre-trained word embeddings. I have not played with other language than latin-based ones, so I is not clear for me how to train character level embeddings for Chinesse. Thus I would simply remove the character level embedding in the config file (`token_characters`).
