### ISSUE TITLE
AllenNLP library version used in this code

### ISSUE THREAD

**Issue by adymaharana** [huggingface/hmtl#6]
Hi, 

I have been running into some Import Errors when I run the HMTL code. Specifically, 
``from allennlp.nn.util import last_dim_softmax, weighted_sum
ImportError: cannot import name 'last_dim_softmax'

I can't find this module in the AllenNLP docs either, so I am assuming that the AllenNLP version used for this code is not the latest. Could you please let us know what version of AllenNLP has been used? 
Thanks!

**Comment by VictorSanh** [comment]
Hello,

Thanks for your interest.

The version of AllenNLP we use is not the latest one: we use `allennlp==0.7.0`.
All the versions of the packages are listed in the file `requirements.txt`. Please refer to the section of `Dependecies and installation` in the README for more details on how to setup a clean environment.

Victor

**Comment by adymaharana** [comment]
Ah right, the requirements.txt file. Sorry, my bad. Thank you for the quick response and interesting work!
