### ISSUE TITLE
this is really cool any plans on porting this to bert? 

### ISSUE THREAD

**Issue by asafamr** [huggingface/hmtl#7]

**Comment by VictorSanh** [comment]
Hey,
Glad to hear that you find it interesting! 🤗
Yes, I do have some experiments in the pipeline. It's just taking a bit of time since it's not my top priority right now, but something will come out eventually!

**Comment by asafamr** [comment]
nice! looking forward to see this :)

**Comment by samru-rai** [comment]
I would also be super excited about this. Any updates yet on this issue?
