### ISSUE TITLE
Can the trained models be uploaded?

### ISSUE THREAD

**Issue by Arjunsankarlal** [huggingface/hmtl#9]
It would be very helpful if the trained model is uploaded.

**Comment by VictorSanh** [comment]
Hello!

We already attached the pre-trained weights when we released the online demo.
It's basically just a `git lfs pull` (have a look at the `demo` folder for more details).
I have updated the main README, maybe it was not clear enough!

Victor

**Comment by Arjunsankarlal** [comment]
Thanks @VictorSanh :)
